server:
  port: 8082
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:7778/mechanical?user=mechanical&password=mechanical123&useSSl=false
    username: mechanical
    password: mechanical23
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    io.swagger.models.parameters.AbstractSerializableParameter: error